engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.scss"

exclude_paths:
  - public/**/*
  - .codeclimate.yml
